### PR TITLE
Resolve #27: Fulltext search minor issue

### LINKED ISSUE #27: Fulltext search minor issue
I think it should start search for usernames which start with "El" and then go through others.

Check this - I wanna find "Eldenroot" - so I typed "el" -> it displays first users with "el" 

image

BUT it should prioritise the usernames which match at the beginning first in my opinion (same behaviour like GitHub)

image

@lairdshaw you did check the library code in past, is that possible?

### PR DESCRIPTION
**Pull request by lairdshaw**
Resolves #27.

Prioritise matches at the beginning of a username in fulltext matching
mode.

Make some unrelated minor changes to code for consistent style.

Note: version number not updated.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Unfortunately not working... no pop-up is displayed when you add any symbol (without any symbol it displays at least thre
ad participants). 

EDIT: hmm, really weird... no items are displayed when I wanna write "Eld" but for other users works... I cannot find my username... weird

**Comment by lairdshaw** [comment]
Hmm. That *is* strange. You're a member of the forum (Psience Quest) whose local mirror I'm developing/testing on, and I can confirm that when I type "`@Eld`", your username pops up. Same for my own username, which is the other possibility it seems meaningful to test: when I type "`@Lai`", my username pops up. So, it's a case of "can't replicate" for me here.

Can you please open Web Developer Tools and check what the return of the AJAX query is when you type out the start of your username - and whether there even is a query being made to your server?

**Comment by Eldenroot** [comment]
Tested and this last commit fixed the issue! Now I am happy and all is working.

@martec - please can you merge it? Also unicode support is fine now.

**Comment by martec** [comment]
thanks for improvement @lairdshaw
merged.

**Pull request merged**
