### PR TITLE
Correct an atwho setting name: lim => limit

### PR DESCRIPTION
**Pull request by lairdshaw**

### CODE REVIEW

**Comment by martec** [comment]
Hi,

thanks.
I just don't know why I made a mistake like that.

**Comment by lairdshaw** [comment]
Hey, it's an easy mistake to make. It wouldn't have been too bad to leave it uncorrected anyway - the height of the pop-up doesn't seem to change when the default of five is increased, and when there are six or more members listed, vertical scrollbars appear, and the up/down arrow keys don't scroll - you have to use the mouse wheel or drag the scrollbars.

**Comment by martec** [comment]
I would never realize since testing with a clean install doesn't have enough members to see it. So again thanks for the correction.

**Comment by lairdshaw** [comment]
No problem. By the way, I've installed the plugin on Psience Quest as I said I would. Let's see what bites we get from this announcement post...

https://psiencequest.net/forums/thread-info-about-newly-installed-plugins-themes-other-features?pid=42151#pid42151

**Comment by martec** [comment]
I am happy that this plugin is being useful for you.

**Pull request merged**
